cabal-version: 3.4
name: hydra-pleco-api
version: 0.1.0.0
synopsis: Shared API types for hydra-pleco
description:
  See README.md for more details

license: MIT
author: Sean D Gillespie
maintainer: Sean D Gillespie <sean@mistersg.net>
copyright: 2026 Sean D Gillespie
category: Development
build-type: Simple
tested-with: ghc ==9.10.*

common common-options
  build-depends:
    aeson,
    base >=4.16 && <5,
    http-media,
    openapi3,
    optics,
    optics-extra,
    relude,
    servant,
    servant-openapi3,
    servant-swagger-ui,
    unliftio,

  mixins:
    base hiding (Prelude),
    relude (Relude as Prelude),
    relude,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wderiving-defaults
    -Wmissing-deriving-strategies
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -Wnoncanonical-monad-instances
    -fhide-source-paths
    -Wmissing-export-lists
    -Wpartial-fields

  default-extensions:
    DataKinds
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    KindSignatures
    LambdaCase
    OverloadedLabels
    OverloadedStrings
    RecordWildCards
    TypeOperators

  default-language: GHC2021

library
  import: common-options
  hs-source-dirs: src
  exposed-modules:
    Hydra.Pleco.Api

library testlib
  import: common-options
  hs-source-dirs: testlib
  exposed-modules:
    Hydra.Pleco.Api.Gen

  build-depends:
    hedgehog,
    hydra-pleco-api,

test-suite tests
  import: common-options
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules:
    Hydra.Pleco.ApiSpec

  build-depends:
    hedgehog,
    hspec,
    hspec-hedgehog,
    hydra-pleco-api,
    hydra-pleco-api:testlib,

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N
